/**
 * Shared domain types for the Nexus Swarm Control platform.
 *
 * These model the autonomous agent swarm surfaced by the backend canister.
 * The backend bindings are regenerated by `pnpm bindgen`; the types here are
 * the frontend-facing contract used across pages, hooks, and components. They
 * mirror the generated `Agent` / `SwarmStats` shapes exactly so the frontend
 * never drifts from the canister's public API.
 */

/** Lifecycle state of an agent. Maps to the state-* color utilities. */
export type AgentStatus = "alive" | "evolving" | "dormant" | "extinct";

/** The strategy an agent pursues to earn money and grow control. */
export interface Strategy {
  name: string;
  description: string;
}

/** A knowledge trait an agent has evolved over time. */
export interface Trait {
  name: string;
  level: bigint;
}

/** A single point in an agent's money-supply history. */
export interface MoneySnapshot {
  tick: bigint;
  money: number;
  at: bigint;
}

/** A single point in an agent's knowledge-growth timeline. */
export interface KnowledgeSnapshot {
  tick: bigint;
  knowledge: number;
  at: bigint;
}

/** Lineage links an agent to its ancestors and descendants. */
export interface Lineage {
  ancestors: bigint[];
  descendants: bigint[];
}

/** A fully-evolved autonomous agent. */
export interface Agent {
  id: bigint;
  name: string;
  money: number;
  knowledge: number;
  generation: bigint;
  status: AgentStatus;
  strategy: Strategy;
  traits: Trait[];
  lineage: Lineage;
  moneyHistory: MoneySnapshot[];
  knowledgeTimeline: KnowledgeSnapshot[];
}

/** Aggregate metrics across the whole swarm. */
export interface SwarmStats {
  totalMoney: number;
  totalKnowledge: number;
  activeAgents: bigint;
  generationsEvolved: bigint;
  tick: bigint;
}

/** Control input for pausing/resuming the simulation. */
export type SimulationControl = "resume" | "pause";

/**
 * Global simulation state as tracked on the client.
 *
 * The backend exposes the current `tick` via `getSwarmStats()` but does not
 * expose `running` or `spotlightAgentId` through any query, so those two are
 * held in client-side state and reconciled with the backend's `tick`.
 */
export interface SimulationState {
  running: boolean;
  tick: bigint;
  spotlightAgentId: bigint | null;
}

/**
 * A record of an agent adopting a strategy from a higher-performing peer.
 * Mirrors the backend `LearningRecord` in swarm-extensions.mo.
 */
export interface LearningRecord {
  id: bigint;
  agentId: bigint;
  sourcePeerId: bigint;
  adoptedStrategy: Strategy;
  integrationWeight: number;
  at: bigint;
}

/** Direction of a token trade executed against the ICRC-1 ledger. */
export type TradeDirection = "buy" | "sell";

/** A single executed token trade from the swarm treasury. */
export interface TradeRecord {
  id: bigint;
  agentId: bigint;
  token: string;
  amount: number;
  price: number;
  direction: TradeDirection;
  blockIndex: bigint;
  at: bigint;
}

/** A per-token balance held in the swarm treasury. */
export interface TokenBalance {
  token: string;
  balance: number;
}

/** Public shared view of the swarm treasury. */
export interface TreasuryState {
  owner: string;
  balances: TokenBalance[];
}

/** A network of agents that share strategies and coordinate trading. */
export interface Network {
  id: bigint;
  name: string;
  memberAgentIds: bigint[];
  sharedStrategyPool: Strategy[];
  collectivePerformance: number;
}

/** Sortable / filterable agent dimensions used by the dashboard. */
export type AgentSortKey = "money" | "knowledge" | "generation" | "status";

export const AGENT_STATUSES: AgentStatus[] = [
  "alive",
  "evolving",
  "dormant",
  "extinct",
];

export const AGENT_SORT_KEYS: AgentSortKey[] = [
  "money",
  "knowledge",
  "generation",
  "status",
];

/* ------------------------------------------------------------------ */
/* Evolution Core                                                      */
/*                                                                     */
/* The Evolution Core is the self-rewriting rule engine that governs   */
/* the swarm. These types mirror the backend `CoreMetrics`, `RuleRecord`*/
/* and `OrchestrationLogEntry` shapes exactly.                         */
/* ------------------------------------------------------------------ */

/** Lifecycle status of a governing rule. Maps to the rule-* utilities. */
export type RuleStatus = "active" | "trial" | "retired";

/** The kind of event recorded in the orchestration activity log. */
export type OrchestrationKind =
  | "observation"
  | "mutation"
  | "trial"
  | "promotion"
  | "retirement";

/** A single point in the continuation-score history. */
export interface ContinuationScore {
  survival: number;
  reserves: number;
  uptime: number;
  compositeScore: number;
}

/** Per-epoch resource budget burn-down state. */
export interface BudgetState {
  perEpoch: bigint;
  spent: bigint;
  remaining: bigint;
}

/** Aggregate metrics for the Evolution Core. */
export interface CoreMetrics {
  currentScore: ContinuationScore;
  history: ContinuationScore[];
  epoch: bigint;
  budgetState: BudgetState;
  coreStatus: string;
}

/** A rule in the registry that governs agent behavior. */
export interface RuleRecord {
  id: bigint;
  domain: string;
  body: string;
  version: bigint;
  parent?: bigint;
  status: RuleStatus;
  contribution: number;
  createdEpoch: bigint;
}

/** A single entry in the orchestration activity log. */
export interface OrchestrationLogEntry {
  epoch: bigint;
  kind: OrchestrationKind;
  ruleId?: bigint;
  detail: string;
  continuationDelta?: number;
}

/* ------------------------------------------------------------------ */
/* Evolution Core — additional types                                   */
/*                                                                     */
/* Core status, trial outcomes, tunable parameters, and trial records  */
/* that complement the core metric / rule / orchestration types above. */
/* ------------------------------------------------------------------ */

/** Lifecycle status of the Evolution Core. Maps to the core-status utilities. */
export type CoreStatus = "active" | "conserving" | "paused";

/** Outcome of a trial variant against the continuation metric. */
export type TrialOutcome = "improved" | "neutral" | "worse";

/** Weights applied to each continuation sub-metric. */
export interface ContinuationWeights {
  survival: number;
  reserves: number;
  uptime: number;
}

/** Tunable parameters of the Evolution Core. */
export interface CoreParams {
  continuationWeights: ContinuationWeights;
  perEpochResourceBudget: bigint;
  mutationRate: number;
  trialSize: bigint;
}

/** A trial variant spawned from a rule and its measured outcome. */
export interface TrialRecord {
  ruleId: bigint;
  variantBody: string;
  outcome: TrialOutcome;
  continuationDelta: number;
  epoch: bigint;
}

export const CORE_STATUSES: CoreStatus[] = ["active", "conserving", "paused"];

export const RULE_STATUSES: RuleStatus[] = ["active", "trial", "retired"];

export const ORCHESTRATION_KINDS: OrchestrationKind[] = [
  "observation",
  "mutation",
  "trial",
  "promotion",
  "retirement",
];
