/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Agent {
  'id' : bigint,
  'status' : AgentStatus,
  'money' : number,
  'lineage' : Lineage,
  'strategy' : Strategy,
  'traits' : Array<Trait>,
  'name' : string,
  'generation' : bigint,
  'knowledgeTimeline' : Array<KnowledgeSnapshot>,
  'knowledge' : number,
  'moneyHistory' : Array<MoneySnapshot>,
}
export type AgentStatus = { 'alive' : null } |
  { 'extinct' : null } |
  { 'dormant' : null } |
  { 'evolving' : null };
export interface Budget {
  'id' : bigint,
  'owner' : UserId,
  'monthlyLimit' : number,
  'category' : string,
}
export interface BudgetInput { 'monthlyLimit' : number, 'category' : string }
export interface BudgetState {
  'perEpoch' : bigint,
  'spent' : bigint,
  'remaining' : bigint,
}
export interface Cell { 'value' : Value, 'name' : string }
export interface ContinuationScore {
  'reserves' : number,
  'survival' : number,
  'uptime' : number,
  'compositeScore' : number,
}
export interface Contribution { 'date' : Timestamp, 'amount' : number }
export interface CoreMetrics {
  'history' : Array<ContinuationScore>,
  'epoch' : bigint,
  'budgetState' : BudgetState,
  'currentScore' : ContinuationScore,
  'coreStatus' : string,
}
export type Error = { 'FrontendOriginsNotConfigured' : null } |
  {
    'MixedSsoSources' : {
      'otherKeys' : Array<string>,
      'ssoKeys' : Array<string>,
    }
  } |
  { 'Stale' : { 'ageNs' : bigint } } |
  { 'MalformedCandid' : null } |
  { 'AmbiguousAttribute' : { 'field' : string, 'sources' : Array<string> } } |
  { 'NoAttributes' : null } |
  { 'UnknownNonce' : null } |
  { 'UntrustedSsoSource' : { 'domain' : string } } |
  { 'MissingField' : string } |
  { 'FrontendOriginMismatch' : { 'got' : string, 'expected' : Array<string> } };
export interface KnowledgeSnapshot {
  'at' : Timestamp,
  'tick' : bigint,
  'knowledge' : number,
}
export interface LearningRecord {
  'at' : Timestamp,
  'id' : bigint,
  'sourcePeerId' : bigint,
  'adoptedStrategy' : Strategy,
  'integrationWeight' : number,
  'agentId' : bigint,
}
export interface Lineage {
  'descendants' : Array<bigint>,
  'ancestors' : Array<bigint>,
}
export interface MoneySnapshot {
  'at' : Timestamp,
  'money' : number,
  'tick' : bigint,
}
export interface Network {
  'id' : bigint,
  'collectivePerformance' : number,
  'name' : string,
  'memberAgentIds' : Array<bigint>,
  'sharedStrategyPool' : Array<Strategy>,
}
export type OrchestrationKind = { 'trial' : null } |
  { 'promotion' : null } |
  { 'observation' : null } |
  { 'retirement' : null } |
  { 'mutation' : null };
export interface OrchestrationLogEntry {
  'ruleId' : [] | [bigint],
  'kind' : OrchestrationKind,
  'continuationDelta' : [] | [number],
  'detail' : string,
  'epoch' : bigint,
}
export interface Result { 'hasMore' : boolean, 'rows' : Array<Array<Cell>> }
export type Result__1 = { 'ok' : null } |
  { 'err' : Error };
export interface RuleRecord {
  'id' : bigint,
  'status' : RuleStatus,
  'domain' : string,
  'body' : string,
  'version' : bigint,
  'contribution' : number,
  'parent' : [] | [bigint],
  'createdEpoch' : bigint,
}
export type RuleStatus = { 'trial' : null } |
  { 'active' : null } |
  { 'retired' : null };
export interface SavingsGoal {
  'id' : bigint,
  'contributions' : Array<Contribution>,
  'owner' : UserId,
  'name' : string,
  'targetAmount' : number,
  'targetDate' : Timestamp,
}
export interface SavingsGoalInput {
  'name' : string,
  'targetAmount' : number,
  'targetDate' : Timestamp,
}
export type SimulationControl = { 'resume' : null } |
  { 'pause' : null };
export interface Strategy { 'name' : string, 'description' : string }
export interface SwarmStats {
  'totalMoney' : number,
  'tick' : bigint,
  'generationsEvolved' : bigint,
  'totalKnowledge' : number,
  'activeAgents' : bigint,
}
export type Timestamp = bigint;
export interface TokenBalance { 'token' : string, 'balance' : number }
export type TradeDirection = { 'buy' : null } |
  { 'sell' : null };
export interface TradeRecord {
  'at' : Timestamp,
  'id' : bigint,
  'direction' : TradeDirection,
  'token' : string,
  'agentId' : bigint,
  'blockIndex' : bigint,
  'price' : number,
  'amount' : number,
}
export interface Trait { 'name' : string, 'level' : bigint }
export interface Transaction {
  'id' : bigint,
  'owner' : UserId,
  'date' : Timestamp,
  'kind' : TransactionType,
  'note' : string,
  'category' : string,
  'amount' : number,
}
export interface TransactionInput {
  'date' : Timestamp,
  'kind' : TransactionType,
  'note' : string,
  'category' : string,
  'amount' : number,
}
export type TransactionType = { 'expense' : null } |
  { 'income' : null };
export interface TreasuryState {
  'owner' : UserId,
  'balances' : Array<TokenBalance>,
}
export type UserId = Principal;
export interface UserProfile {
  'currency' : string,
  'onboardingCompleted' : boolean,
  'startingBalance' : number,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type Value = { 'int' : bigint } |
  { 'nat' : bigint } |
  { 'float' : number } |
  { 'bool' : boolean } |
  { 'null' : null } |
  { 'text' : string };
export interface _SERVICE {
  '_initialize_access_control' : ActorMethod<[], undefined>,
  '_internet_identity_sign_in_finish' : ActorMethod<[], Result__1>,
  '_internet_identity_sign_in_start' : ActorMethod<[], Uint8Array>,
  'addBudget' : ActorMethod<[BudgetInput], bigint>,
  'addContribution' : ActorMethod<[bigint, number], undefined>,
  'addSavingsGoal' : ActorMethod<[SavingsGoalInput], bigint>,
  'addTransaction' : ActorMethod<[TransactionInput], bigint>,
  'advanceEpoch' : ActorMethod<[], CoreMetrics>,
  'advanceTick' : ActorMethod<[], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createNetwork' : ActorMethod<[string], bigint>,
  'deleteBudget' : ActorMethod<[bigint], undefined>,
  'deleteSavingsGoal' : ActorMethod<[bigint], undefined>,
  'deleteTransaction' : ActorMethod<[bigint], undefined>,
  'execute' : ActorMethod<[string], Result>,
  'executeTrade' : ActorMethod<
    [bigint, string, number, number, TradeDirection],
    undefined
  >,
  'fundTreasury' : ActorMethod<[string, number], undefined>,
  'getAgent' : ActorMethod<[bigint], [] | [Agent]>,
  'getAgentLearning' : ActorMethod<[bigint], Array<LearningRecord>>,
  'getAgentTrades' : ActorMethod<[bigint], Array<TradeRecord>>,
  'getApiDoc' : ActorMethod<[], string>,
  'getBudget' : ActorMethod<[bigint], [] | [Budget]>,
  'getCallerProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCoreMetrics' : ActorMethod<[], CoreMetrics>,
  'getNetwork' : ActorMethod<[bigint], [] | [Network]>,
  'getRule' : ActorMethod<[bigint], [] | [RuleRecord]>,
  'getSavingsGoal' : ActorMethod<[bigint], [] | [SavingsGoal]>,
  'getSwarmStats' : ActorMethod<[], SwarmStats>,
  'getTransaction' : ActorMethod<[bigint], [] | [Transaction]>,
  'getTreasury' : ActorMethod<[], TreasuryState>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'joinNetwork' : ActorMethod<[bigint, bigint], undefined>,
  'leaveNetwork' : ActorMethod<[bigint, bigint], undefined>,
  'listAgents' : ActorMethod<[], Array<Agent>>,
  'listBudgets' : ActorMethod<[], Array<Budget>>,
  'listLearningRecords' : ActorMethod<[], Array<LearningRecord>>,
  'listNetworks' : ActorMethod<[], Array<Network>>,
  'listOrchestrationLog' : ActorMethod<[], Array<OrchestrationLogEntry>>,
  'listRules' : ActorMethod<[], Array<RuleRecord>>,
  'listSavingsGoals' : ActorMethod<[], Array<SavingsGoal>>,
  'listTrades' : ActorMethod<[], Array<TradeRecord>>,
  'listTransactions' : ActorMethod<[], Array<Transaction>>,
  'observeAndLearn' : ActorMethod<
    [bigint, bigint, Strategy, number],
    undefined
  >,
  'resetEvolutionCore' : ActorMethod<[], undefined>,
  'resetSwarm' : ActorMethod<[], undefined>,
  'saveCallerProfile' : ActorMethod<[UserProfile], undefined>,
  'schema' : ActorMethod<[], string>,
  'setSimulationControl' : ActorMethod<[SimulationControl], undefined>,
  'spotlightAgent' : ActorMethod<[bigint], undefined>,
  'updateBudget' : ActorMethod<[bigint, BudgetInput], undefined>,
  'updateSavingsGoal' : ActorMethod<[bigint, SavingsGoalInput], undefined>,
  'updateTransaction' : ActorMethod<[bigint, TransactionInput], undefined>,
  'withdrawTreasury' : ActorMethod<[string, number], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];