/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Error = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const BudgetInput = IDL.Record({
  'monthlyLimit' : IDL.Float64,
  'category' : IDL.Text,
});
export const Timestamp = IDL.Int;
export const SavingsGoalInput = IDL.Record({
  'name' : IDL.Text,
  'targetAmount' : IDL.Float64,
  'targetDate' : Timestamp,
});
export const TransactionType = IDL.Variant({
  'expense' : IDL.Null,
  'income' : IDL.Null,
});
export const TransactionInput = IDL.Record({
  'date' : Timestamp,
  'kind' : TransactionType,
  'note' : IDL.Text,
  'category' : IDL.Text,
  'amount' : IDL.Float64,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Value = IDL.Variant({
  'int' : IDL.Int,
  'nat' : IDL.Nat,
  'float' : IDL.Float64,
  'bool' : IDL.Bool,
  'null' : IDL.Null,
  'text' : IDL.Text,
});
export const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
export const Result = IDL.Record({
  'hasMore' : IDL.Bool,
  'rows' : IDL.Vec(IDL.Vec(Cell)),
});
export const TradeDirection = IDL.Variant({
  'buy' : IDL.Null,
  'sell' : IDL.Null,
});
export const AgentStatus = IDL.Variant({
  'alive' : IDL.Null,
  'extinct' : IDL.Null,
  'dormant' : IDL.Null,
  'evolving' : IDL.Null,
});
export const Lineage = IDL.Record({
  'descendants' : IDL.Vec(IDL.Nat),
  'ancestors' : IDL.Vec(IDL.Nat),
});
export const Strategy = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const Trait = IDL.Record({ 'name' : IDL.Text, 'level' : IDL.Nat });
export const KnowledgeSnapshot = IDL.Record({
  'at' : Timestamp,
  'tick' : IDL.Nat,
  'knowledge' : IDL.Float64,
});
export const MoneySnapshot = IDL.Record({
  'at' : Timestamp,
  'money' : IDL.Float64,
  'tick' : IDL.Nat,
});
export const Agent = IDL.Record({
  'id' : IDL.Nat,
  'status' : AgentStatus,
  'money' : IDL.Float64,
  'lineage' : Lineage,
  'strategy' : Strategy,
  'traits' : IDL.Vec(Trait),
  'name' : IDL.Text,
  'generation' : IDL.Nat,
  'knowledgeTimeline' : IDL.Vec(KnowledgeSnapshot),
  'knowledge' : IDL.Float64,
  'moneyHistory' : IDL.Vec(MoneySnapshot),
});
export const LearningRecord = IDL.Record({
  'at' : Timestamp,
  'id' : IDL.Nat,
  'sourcePeerId' : IDL.Nat,
  'adoptedStrategy' : Strategy,
  'integrationWeight' : IDL.Float64,
  'agentId' : IDL.Nat,
});
export const TradeRecord = IDL.Record({
  'at' : Timestamp,
  'id' : IDL.Nat,
  'direction' : TradeDirection,
  'token' : IDL.Text,
  'agentId' : IDL.Nat,
  'blockIndex' : IDL.Nat,
  'price' : IDL.Float64,
  'amount' : IDL.Float64,
});
export const UserId = IDL.Principal;
export const Budget = IDL.Record({
  'id' : IDL.Nat,
  'owner' : UserId,
  'monthlyLimit' : IDL.Float64,
  'category' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'currency' : IDL.Text,
  'onboardingCompleted' : IDL.Bool,
  'startingBalance' : IDL.Float64,
});
export const Network = IDL.Record({
  'id' : IDL.Nat,
  'collectivePerformance' : IDL.Float64,
  'name' : IDL.Text,
  'memberAgentIds' : IDL.Vec(IDL.Nat),
  'sharedStrategyPool' : IDL.Vec(Strategy),
});
export const Contribution = IDL.Record({
  'date' : Timestamp,
  'amount' : IDL.Float64,
});
export const SavingsGoal = IDL.Record({
  'id' : IDL.Nat,
  'contributions' : IDL.Vec(Contribution),
  'owner' : UserId,
  'name' : IDL.Text,
  'targetAmount' : IDL.Float64,
  'targetDate' : Timestamp,
});
export const SwarmStats = IDL.Record({
  'totalMoney' : IDL.Float64,
  'tick' : IDL.Nat,
  'generationsEvolved' : IDL.Nat,
  'totalKnowledge' : IDL.Float64,
  'activeAgents' : IDL.Nat,
});
export const Transaction = IDL.Record({
  'id' : IDL.Nat,
  'owner' : UserId,
  'date' : Timestamp,
  'kind' : TransactionType,
  'note' : IDL.Text,
  'category' : IDL.Text,
  'amount' : IDL.Float64,
});
export const TokenBalance = IDL.Record({
  'token' : IDL.Text,
  'balance' : IDL.Float64,
});
export const TreasuryState = IDL.Record({
  'owner' : UserId,
  'balances' : IDL.Vec(TokenBalance),
});
export const SimulationControl = IDL.Variant({
  'resume' : IDL.Null,
  'pause' : IDL.Null,
});

export const idlService = IDL.Service({
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'addBudget' : IDL.Func([BudgetInput], [IDL.Nat], []),
  'addContribution' : IDL.Func([IDL.Nat, IDL.Float64], [], []),
  'addSavingsGoal' : IDL.Func([SavingsGoalInput], [IDL.Nat], []),
  'addTransaction' : IDL.Func([TransactionInput], [IDL.Nat], []),
  'advanceTick' : IDL.Func([], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createNetwork' : IDL.Func([IDL.Text], [IDL.Nat], []),
  'deleteBudget' : IDL.Func([IDL.Nat], [], []),
  'deleteSavingsGoal' : IDL.Func([IDL.Nat], [], []),
  'deleteTransaction' : IDL.Func([IDL.Nat], [], []),
  'execute' : IDL.Func([IDL.Text], [Result], ['query']),
  'executeTrade' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Float64, IDL.Float64, TradeDirection],
      [],
      [],
    ),
  'fundTreasury' : IDL.Func([IDL.Text, IDL.Float64], [], []),
  'getAgent' : IDL.Func([IDL.Nat], [IDL.Opt(Agent)], ['query']),
  'getAgentLearning' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(LearningRecord)],
      ['query'],
    ),
  'getAgentTrades' : IDL.Func([IDL.Nat], [IDL.Vec(TradeRecord)], ['query']),
  'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
  'getBudget' : IDL.Func([IDL.Nat], [IDL.Opt(Budget)], ['query']),
  'getCallerProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getNetwork' : IDL.Func([IDL.Nat], [IDL.Opt(Network)], ['query']),
  'getSavingsGoal' : IDL.Func([IDL.Nat], [IDL.Opt(SavingsGoal)], ['query']),
  'getSwarmStats' : IDL.Func([], [SwarmStats], ['query']),
  'getTransaction' : IDL.Func([IDL.Nat], [IDL.Opt(Transaction)], ['query']),
  'getTreasury' : IDL.Func([], [TreasuryState], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'joinNetwork' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'leaveNetwork' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'listAgents' : IDL.Func([], [IDL.Vec(Agent)], ['query']),
  'listBudgets' : IDL.Func([], [IDL.Vec(Budget)], ['query']),
  'listLearningRecords' : IDL.Func([], [IDL.Vec(LearningRecord)], ['query']),
  'listNetworks' : IDL.Func([], [IDL.Vec(Network)], ['query']),
  'listSavingsGoals' : IDL.Func([], [IDL.Vec(SavingsGoal)], ['query']),
  'listTrades' : IDL.Func([], [IDL.Vec(TradeRecord)], ['query']),
  'listTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'observeAndLearn' : IDL.Func(
      [IDL.Nat, IDL.Nat, Strategy, IDL.Float64],
      [],
      [],
    ),
  'resetSwarm' : IDL.Func([], [], []),
  'saveCallerProfile' : IDL.Func([UserProfile], [], []),
  'schema' : IDL.Func([], [IDL.Text], ['query']),
  'setSimulationControl' : IDL.Func([SimulationControl], [], []),
  'spotlightAgent' : IDL.Func([IDL.Nat], [], []),
  'updateBudget' : IDL.Func([IDL.Nat, BudgetInput], [], []),
  'updateSavingsGoal' : IDL.Func([IDL.Nat, SavingsGoalInput], [], []),
  'updateTransaction' : IDL.Func([IDL.Nat, TransactionInput], [], []),
  'withdrawTreasury' : IDL.Func([IDL.Text, IDL.Float64], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const BudgetInput = IDL.Record({
    'monthlyLimit' : IDL.Float64,
    'category' : IDL.Text,
  });
  const Timestamp = IDL.Int;
  const SavingsGoalInput = IDL.Record({
    'name' : IDL.Text,
    'targetAmount' : IDL.Float64,
    'targetDate' : Timestamp,
  });
  const TransactionType = IDL.Variant({
    'expense' : IDL.Null,
    'income' : IDL.Null,
  });
  const TransactionInput = IDL.Record({
    'date' : Timestamp,
    'kind' : TransactionType,
    'note' : IDL.Text,
    'category' : IDL.Text,
    'amount' : IDL.Float64,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Value = IDL.Variant({
    'int' : IDL.Int,
    'nat' : IDL.Nat,
    'float' : IDL.Float64,
    'bool' : IDL.Bool,
    'null' : IDL.Null,
    'text' : IDL.Text,
  });
  const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
  const Result = IDL.Record({
    'hasMore' : IDL.Bool,
    'rows' : IDL.Vec(IDL.Vec(Cell)),
  });
  const TradeDirection = IDL.Variant({ 'buy' : IDL.Null, 'sell' : IDL.Null });
  const AgentStatus = IDL.Variant({
    'alive' : IDL.Null,
    'extinct' : IDL.Null,
    'dormant' : IDL.Null,
    'evolving' : IDL.Null,
  });
  const Lineage = IDL.Record({
    'descendants' : IDL.Vec(IDL.Nat),
    'ancestors' : IDL.Vec(IDL.Nat),
  });
  const Strategy = IDL.Record({ 'name' : IDL.Text, 'description' : IDL.Text });
  const Trait = IDL.Record({ 'name' : IDL.Text, 'level' : IDL.Nat });
  const KnowledgeSnapshot = IDL.Record({
    'at' : Timestamp,
    'tick' : IDL.Nat,
    'knowledge' : IDL.Float64,
  });
  const MoneySnapshot = IDL.Record({
    'at' : Timestamp,
    'money' : IDL.Float64,
    'tick' : IDL.Nat,
  });
  const Agent = IDL.Record({
    'id' : IDL.Nat,
    'status' : AgentStatus,
    'money' : IDL.Float64,
    'lineage' : Lineage,
    'strategy' : Strategy,
    'traits' : IDL.Vec(Trait),
    'name' : IDL.Text,
    'generation' : IDL.Nat,
    'knowledgeTimeline' : IDL.Vec(KnowledgeSnapshot),
    'knowledge' : IDL.Float64,
    'moneyHistory' : IDL.Vec(MoneySnapshot),
  });
  const LearningRecord = IDL.Record({
    'at' : Timestamp,
    'id' : IDL.Nat,
    'sourcePeerId' : IDL.Nat,
    'adoptedStrategy' : Strategy,
    'integrationWeight' : IDL.Float64,
    'agentId' : IDL.Nat,
  });
  const TradeRecord = IDL.Record({
    'at' : Timestamp,
    'id' : IDL.Nat,
    'direction' : TradeDirection,
    'token' : IDL.Text,
    'agentId' : IDL.Nat,
    'blockIndex' : IDL.Nat,
    'price' : IDL.Float64,
    'amount' : IDL.Float64,
  });
  const UserId = IDL.Principal;
  const Budget = IDL.Record({
    'id' : IDL.Nat,
    'owner' : UserId,
    'monthlyLimit' : IDL.Float64,
    'category' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'currency' : IDL.Text,
    'onboardingCompleted' : IDL.Bool,
    'startingBalance' : IDL.Float64,
  });
  const Network = IDL.Record({
    'id' : IDL.Nat,
    'collectivePerformance' : IDL.Float64,
    'name' : IDL.Text,
    'memberAgentIds' : IDL.Vec(IDL.Nat),
    'sharedStrategyPool' : IDL.Vec(Strategy),
  });
  const Contribution = IDL.Record({
    'date' : Timestamp,
    'amount' : IDL.Float64,
  });
  const SavingsGoal = IDL.Record({
    'id' : IDL.Nat,
    'contributions' : IDL.Vec(Contribution),
    'owner' : UserId,
    'name' : IDL.Text,
    'targetAmount' : IDL.Float64,
    'targetDate' : Timestamp,
  });
  const SwarmStats = IDL.Record({
    'totalMoney' : IDL.Float64,
    'tick' : IDL.Nat,
    'generationsEvolved' : IDL.Nat,
    'totalKnowledge' : IDL.Float64,
    'activeAgents' : IDL.Nat,
  });
  const Transaction = IDL.Record({
    'id' : IDL.Nat,
    'owner' : UserId,
    'date' : Timestamp,
    'kind' : TransactionType,
    'note' : IDL.Text,
    'category' : IDL.Text,
    'amount' : IDL.Float64,
  });
  const TokenBalance = IDL.Record({
    'token' : IDL.Text,
    'balance' : IDL.Float64,
  });
  const TreasuryState = IDL.Record({
    'owner' : UserId,
    'balances' : IDL.Vec(TokenBalance),
  });
  const SimulationControl = IDL.Variant({
    'resume' : IDL.Null,
    'pause' : IDL.Null,
  });
  
  return IDL.Service({
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'addBudget' : IDL.Func([BudgetInput], [IDL.Nat], []),
    'addContribution' : IDL.Func([IDL.Nat, IDL.Float64], [], []),
    'addSavingsGoal' : IDL.Func([SavingsGoalInput], [IDL.Nat], []),
    'addTransaction' : IDL.Func([TransactionInput], [IDL.Nat], []),
    'advanceTick' : IDL.Func([], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createNetwork' : IDL.Func([IDL.Text], [IDL.Nat], []),
    'deleteBudget' : IDL.Func([IDL.Nat], [], []),
    'deleteSavingsGoal' : IDL.Func([IDL.Nat], [], []),
    'deleteTransaction' : IDL.Func([IDL.Nat], [], []),
    'execute' : IDL.Func([IDL.Text], [Result], ['query']),
    'executeTrade' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Float64, IDL.Float64, TradeDirection],
        [],
        [],
      ),
    'fundTreasury' : IDL.Func([IDL.Text, IDL.Float64], [], []),
    'getAgent' : IDL.Func([IDL.Nat], [IDL.Opt(Agent)], ['query']),
    'getAgentLearning' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(LearningRecord)],
        ['query'],
      ),
    'getAgentTrades' : IDL.Func([IDL.Nat], [IDL.Vec(TradeRecord)], ['query']),
    'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
    'getBudget' : IDL.Func([IDL.Nat], [IDL.Opt(Budget)], ['query']),
    'getCallerProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getNetwork' : IDL.Func([IDL.Nat], [IDL.Opt(Network)], ['query']),
    'getSavingsGoal' : IDL.Func([IDL.Nat], [IDL.Opt(SavingsGoal)], ['query']),
    'getSwarmStats' : IDL.Func([], [SwarmStats], ['query']),
    'getTransaction' : IDL.Func([IDL.Nat], [IDL.Opt(Transaction)], ['query']),
    'getTreasury' : IDL.Func([], [TreasuryState], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'joinNetwork' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'leaveNetwork' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'listAgents' : IDL.Func([], [IDL.Vec(Agent)], ['query']),
    'listBudgets' : IDL.Func([], [IDL.Vec(Budget)], ['query']),
    'listLearningRecords' : IDL.Func([], [IDL.Vec(LearningRecord)], ['query']),
    'listNetworks' : IDL.Func([], [IDL.Vec(Network)], ['query']),
    'listSavingsGoals' : IDL.Func([], [IDL.Vec(SavingsGoal)], ['query']),
    'listTrades' : IDL.Func([], [IDL.Vec(TradeRecord)], ['query']),
    'listTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
    'observeAndLearn' : IDL.Func(
        [IDL.Nat, IDL.Nat, Strategy, IDL.Float64],
        [],
        [],
      ),
    'resetSwarm' : IDL.Func([], [], []),
    'saveCallerProfile' : IDL.Func([UserProfile], [], []),
    'schema' : IDL.Func([], [IDL.Text], ['query']),
    'setSimulationControl' : IDL.Func([SimulationControl], [], []),
    'spotlightAgent' : IDL.Func([IDL.Nat], [], []),
    'updateBudget' : IDL.Func([IDL.Nat, BudgetInput], [], []),
    'updateSavingsGoal' : IDL.Func([IDL.Nat, SavingsGoalInput], [], []),
    'updateTransaction' : IDL.Func([IDL.Nat, TransactionInput], [], []),
    'withdrawTreasury' : IDL.Func([IDL.Text, IDL.Float64], [], []),
  });
};

export const init = ({ IDL }) => { return []; };