/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
import { ExternalBlob } from "@caffeineai/object-storage";
export { ExternalBlob } from "@caffeineai/object-storage";
export type Timestamp = bigint;
export interface OrchestrationLogEntry {
    ruleId?: bigint;
    kind: OrchestrationKind;
    continuationDelta?: number;
    detail: string;
    epoch: bigint;
}
export interface SwarmStats {
    totalMoney: number;
    tick: bigint;
    generationsEvolved: bigint;
    totalKnowledge: number;
    activeAgents: bigint;
}
export type Result__1 = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
};
export interface MoneySnapshot {
    at: Timestamp;
    money: number;
    tick: bigint;
}
export interface Transaction {
    id: bigint;
    owner: UserId;
    date: Timestamp;
    kind: TransactionType;
    note: string;
    category: string;
    amount: number;
}
export interface Trait {
    name: string;
    level: bigint;
}
export interface BudgetState {
    perEpoch: bigint;
    spent: bigint;
    remaining: bigint;
}
export interface LearningRecord {
    at: Timestamp;
    id: bigint;
    sourcePeerId: bigint;
    adoptedStrategy: Strategy;
    integrationWeight: number;
    agentId: bigint;
}
export interface RuleRecord {
    id: bigint;
    status: RuleStatus;
    domain: string;
    body: string;
    version: bigint;
    contribution: number;
    parent?: bigint;
    createdEpoch: bigint;
}
export interface Cell {
    value: Value;
    name: string;
}
export interface SavingsGoalInput {
    name: string;
    targetAmount: number;
    targetDate: Timestamp;
}
export interface Contribution {
    date: Timestamp;
    amount: number;
}
export interface TreasuryState {
    owner: UserId;
    balances: Array<TokenBalance>;
}
export interface Strategy {
    name: string;
    description: string;
}
export interface TransactionInput {
    date: Timestamp;
    kind: TransactionType;
    note: string;
    category: string;
    amount: number;
}
export interface SavingsGoal {
    id: bigint;
    contributions: Array<Contribution>;
    owner: UserId;
    name: string;
    targetAmount: number;
    targetDate: Timestamp;
}
export type Value = {
    __kind__: "int";
    int: bigint;
} | {
    __kind__: "nat";
    nat: bigint;
} | {
    __kind__: "float";
    float: number;
} | {
    __kind__: "bool";
    bool: boolean;
} | {
    __kind__: "null";
    null: null;
} | {
    __kind__: "text";
    text: string;
};
export interface BudgetInput {
    monthlyLimit: number;
    category: string;
}
export interface Agent {
    id: bigint;
    status: AgentStatus;
    money: number;
    lineage: Lineage;
    strategy: Strategy;
    traits: Array<Trait>;
    name: string;
    generation: bigint;
    knowledgeTimeline: Array<KnowledgeSnapshot>;
    knowledge: number;
    moneyHistory: Array<MoneySnapshot>;
}
export type Error_ = {
    __kind__: "FrontendOriginsNotConfigured";
    FrontendOriginsNotConfigured: null;
} | {
    __kind__: "MixedSsoSources";
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    __kind__: "Stale";
    Stale: {
        ageNs: bigint;
    };
} | {
    __kind__: "MalformedCandid";
    MalformedCandid: null;
} | {
    __kind__: "AmbiguousAttribute";
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    __kind__: "NoAttributes";
    NoAttributes: null;
} | {
    __kind__: "UnknownNonce";
    UnknownNonce: null;
} | {
    __kind__: "UntrustedSsoSource";
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    __kind__: "MissingField";
    MissingField: string;
} | {
    __kind__: "FrontendOriginMismatch";
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
};
export interface KnowledgeSnapshot {
    at: Timestamp;
    tick: bigint;
    knowledge: number;
}
export interface CoreMetrics {
    history: Array<ContinuationScore>;
    epoch: bigint;
    budgetState: BudgetState;
    currentScore: ContinuationScore;
    coreStatus: string;
}
export type UserId = Principal;
export interface ContinuationScore {
    reserves: number;
    survival: number;
    uptime: number;
    compositeScore: number;
}
export interface Result {
    hasMore: boolean;
    rows: Array<Array<Cell>>;
}
export interface Network {
    id: bigint;
    collectivePerformance: number;
    name: string;
    memberAgentIds: Array<bigint>;
    sharedStrategyPool: Array<Strategy>;
}
export interface Lineage {
    descendants: Array<bigint>;
    ancestors: Array<bigint>;
}
export interface TradeRecord {
    at: Timestamp;
    id: bigint;
    direction: TradeDirection;
    token: string;
    agentId: bigint;
    blockIndex: bigint;
    price: number;
    amount: number;
}
export interface TokenBalance {
    token: string;
    balance: number;
}
export interface UserProfile {
    currency: string;
    onboardingCompleted: boolean;
    startingBalance: number;
}
export interface Budget {
    id: bigint;
    owner: UserId;
    monthlyLimit: number;
    category: string;
}
export enum AgentStatus {
    alive = "alive",
    extinct = "extinct",
    dormant = "dormant",
    evolving = "evolving"
}
export enum OrchestrationKind {
    trial = "trial",
    promotion = "promotion",
    observation = "observation",
    retirement = "retirement",
    mutation = "mutation"
}
export enum RuleStatus {
    trial = "trial",
    active = "active",
    retired = "retired"
}
export enum SimulationControl {
    resume = "resume",
    pause = "pause"
}
export enum TradeDirection {
    buy = "buy",
    sell = "sell"
}
export enum TransactionType {
    expense = "expense",
    income = "income"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initialize_access_control(): Promise<void>;
    _internet_identity_sign_in_finish(): Promise<Result__1>;
    _internet_identity_sign_in_start(): Promise<Uint8Array>;
    addBudget(input: BudgetInput): Promise<bigint>;
    addContribution(id: bigint, amount: number): Promise<void>;
    addSavingsGoal(input: SavingsGoalInput): Promise<bigint>;
    addTransaction(input: TransactionInput): Promise<bigint>;
    advanceEpoch(): Promise<CoreMetrics>;
    advanceTick(): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createNetwork(name: string): Promise<bigint>;
    deleteBudget(id: bigint): Promise<void>;
    deleteSavingsGoal(id: bigint): Promise<void>;
    deleteTransaction(id: bigint): Promise<void>;
    execute(qJson: string): Promise<Result>;
    executeTrade(agentId: bigint, token: string, amount: number, price: number, direction: TradeDirection): Promise<void>;
    fundTreasury(token: string, amount: number): Promise<void>;
    getAgent(id: bigint): Promise<Agent | null>;
    getAgentLearning(agentId: bigint): Promise<Array<LearningRecord>>;
    getAgentTrades(agentId: bigint): Promise<Array<TradeRecord>>;
    getApiDoc(): Promise<string>;
    getBudget(id: bigint): Promise<Budget | null>;
    getCallerProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCoreMetrics(): Promise<CoreMetrics>;
    getNetwork(networkId: bigint): Promise<Network | null>;
    getRule(id: bigint): Promise<RuleRecord | null>;
    getSavingsGoal(id: bigint): Promise<SavingsGoal | null>;
    getSwarmStats(): Promise<SwarmStats>;
    getTransaction(id: bigint): Promise<Transaction | null>;
    getTreasury(): Promise<TreasuryState>;
    isCallerAdmin(): Promise<boolean>;
    joinNetwork(networkId: bigint, agentId: bigint): Promise<void>;
    leaveNetwork(networkId: bigint, agentId: bigint): Promise<void>;
    listAgents(): Promise<Array<Agent>>;
    listBudgets(): Promise<Array<Budget>>;
    listLearningRecords(): Promise<Array<LearningRecord>>;
    listNetworks(): Promise<Array<Network>>;
    listOrchestrationLog(): Promise<Array<OrchestrationLogEntry>>;
    listRules(): Promise<Array<RuleRecord>>;
    listSavingsGoals(): Promise<Array<SavingsGoal>>;
    listTrades(): Promise<Array<TradeRecord>>;
    listTransactions(): Promise<Array<Transaction>>;
    observeAndLearn(agentId: bigint, sourcePeerId: bigint, adoptedStrategy: Strategy, integrationWeight: number): Promise<void>;
    resetEvolutionCore(): Promise<void>;
    resetSwarm(): Promise<void>;
    saveCallerProfile(profile: UserProfile): Promise<void>;
    schema(): Promise<string>;
    setSimulationControl(control: SimulationControl): Promise<void>;
    spotlightAgent(id: bigint): Promise<void>;
    updateBudget(id: bigint, input: BudgetInput): Promise<void>;
    updateSavingsGoal(id: bigint, input: SavingsGoalInput): Promise<void>;
    updateTransaction(id: bigint, input: TransactionInput): Promise<void>;
    withdrawTreasury(token: string, amount: number): Promise<void>;
}
import type { Agent as _Agent, AgentStatus as _AgentStatus, Budget as _Budget, Cell as _Cell, Error as _Error, KnowledgeSnapshot as _KnowledgeSnapshot, Lineage as _Lineage, MoneySnapshot as _MoneySnapshot, Network as _Network, OrchestrationKind as _OrchestrationKind, OrchestrationLogEntry as _OrchestrationLogEntry, Result as _Result, Result__1 as _Result__1, RuleRecord as _RuleRecord, RuleStatus as _RuleStatus, SavingsGoal as _SavingsGoal, SimulationControl as _SimulationControl, Strategy as _Strategy, Timestamp as _Timestamp, TradeDirection as _TradeDirection, TradeRecord as _TradeRecord, Trait as _Trait, Transaction as _Transaction, TransactionInput as _TransactionInput, TransactionType as _TransactionType, UserId as _UserId, UserProfile as _UserProfile, UserRole as _UserRole, Value as _Value } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initialize_access_control(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initialize_access_control();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initialize_access_control();
            return result;
        }
    }
    async _internet_identity_sign_in_finish(): Promise<Result__1> {
        if (this.processError) {
            try {
                const result = await this.actor._internet_identity_sign_in_finish();
                return from_candid_Result__1_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._internet_identity_sign_in_finish();
            return from_candid_Result__1_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async _internet_identity_sign_in_start(): Promise<Uint8Array> {
        if (this.processError) {
            try {
                const result = await this.actor._internet_identity_sign_in_start();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._internet_identity_sign_in_start();
            return result;
        }
    }
    async addBudget(arg0: BudgetInput): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addBudget(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addBudget(arg0);
            return result;
        }
    }
    async addContribution(arg0: bigint, arg1: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addContribution(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addContribution(arg0, arg1);
            return result;
        }
    }
    async addSavingsGoal(arg0: SavingsGoalInput): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addSavingsGoal(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSavingsGoal(arg0);
            return result;
        }
    }
    async addTransaction(arg0: TransactionInput): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addTransaction(to_candid_TransactionInput_n5(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTransaction(to_candid_TransactionInput_n5(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async advanceEpoch(): Promise<CoreMetrics> {
        if (this.processError) {
            try {
                const result = await this.actor.advanceEpoch();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.advanceEpoch();
            return result;
        }
    }
    async advanceTick(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.advanceTick();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.advanceTick();
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n9(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n9(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createNetwork(arg0: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createNetwork(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createNetwork(arg0);
            return result;
        }
    }
    async deleteBudget(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteBudget(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteBudget(arg0);
            return result;
        }
    }
    async deleteSavingsGoal(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSavingsGoal(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSavingsGoal(arg0);
            return result;
        }
    }
    async deleteTransaction(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTransaction(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTransaction(arg0);
            return result;
        }
    }
    async execute(arg0: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.execute(arg0);
                return from_candid_Result_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.execute(arg0);
            return from_candid_Result_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async executeTrade(arg0: bigint, arg1: string, arg2: number, arg3: number, arg4: TradeDirection): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.executeTrade(arg0, arg1, arg2, arg3, to_candid_TradeDirection_n19(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.executeTrade(arg0, arg1, arg2, arg3, to_candid_TradeDirection_n19(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
    async fundTreasury(arg0: string, arg1: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.fundTreasury(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fundTreasury(arg0, arg1);
            return result;
        }
    }
    async getAgent(arg0: bigint): Promise<Agent | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAgent(arg0);
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAgent(arg0);
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAgentLearning(arg0: bigint): Promise<Array<LearningRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAgentLearning(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAgentLearning(arg0);
            return result;
        }
    }
    async getAgentTrades(arg0: bigint): Promise<Array<TradeRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAgentTrades(arg0);
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAgentTrades(arg0);
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getApiDoc(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getApiDoc();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getApiDoc();
            return result;
        }
    }
    async getBudget(arg0: bigint): Promise<Budget | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBudget(arg0);
                return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBudget(arg0);
            return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerProfile();
                return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerProfile();
            return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCoreMetrics(): Promise<CoreMetrics> {
        if (this.processError) {
            try {
                const result = await this.actor.getCoreMetrics();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCoreMetrics();
            return result;
        }
    }
    async getNetwork(arg0: bigint): Promise<Network | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getNetwork(arg0);
                return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNetwork(arg0);
            return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRule(arg0: bigint): Promise<RuleRecord | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getRule(arg0);
                return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRule(arg0);
            return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSavingsGoal(arg0: bigint): Promise<SavingsGoal | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSavingsGoal(arg0);
                return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSavingsGoal(arg0);
            return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSwarmStats(): Promise<SwarmStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getSwarmStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSwarmStats();
            return result;
        }
    }
    async getTransaction(arg0: bigint): Promise<Transaction | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTransaction(arg0);
                return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTransaction(arg0);
            return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTreasury(): Promise<TreasuryState> {
        if (this.processError) {
            try {
                const result = await this.actor.getTreasury();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTreasury();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async joinNetwork(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.joinNetwork(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.joinNetwork(arg0, arg1);
            return result;
        }
    }
    async leaveNetwork(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.leaveNetwork(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.leaveNetwork(arg0, arg1);
            return result;
        }
    }
    async listAgents(): Promise<Array<Agent>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAgents();
                return from_candid_vec_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAgents();
            return from_candid_vec_n48(this._uploadFile, this._downloadFile, result);
        }
    }
    async listBudgets(): Promise<Array<Budget>> {
        if (this.processError) {
            try {
                const result = await this.actor.listBudgets();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listBudgets();
            return result;
        }
    }
    async listLearningRecords(): Promise<Array<LearningRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.listLearningRecords();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listLearningRecords();
            return result;
        }
    }
    async listNetworks(): Promise<Array<Network>> {
        if (this.processError) {
            try {
                const result = await this.actor.listNetworks();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listNetworks();
            return result;
        }
    }
    async listOrchestrationLog(): Promise<Array<OrchestrationLogEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.listOrchestrationLog();
                return from_candid_vec_n49(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listOrchestrationLog();
            return from_candid_vec_n49(this._uploadFile, this._downloadFile, result);
        }
    }
    async listRules(): Promise<Array<RuleRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.listRules();
                return from_candid_vec_n55(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listRules();
            return from_candid_vec_n55(this._uploadFile, this._downloadFile, result);
        }
    }
    async listSavingsGoals(): Promise<Array<SavingsGoal>> {
        if (this.processError) {
            try {
                const result = await this.actor.listSavingsGoals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listSavingsGoals();
            return result;
        }
    }
    async listTrades(): Promise<Array<TradeRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.listTrades();
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listTrades();
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async listTransactions(): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.listTransactions();
                return from_candid_vec_n56(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listTransactions();
            return from_candid_vec_n56(this._uploadFile, this._downloadFile, result);
        }
    }
    async observeAndLearn(arg0: bigint, arg1: bigint, arg2: Strategy, arg3: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.observeAndLearn(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.observeAndLearn(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async resetEvolutionCore(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.resetEvolutionCore();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resetEvolutionCore();
            return result;
        }
    }
    async resetSwarm(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.resetSwarm();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resetSwarm();
            return result;
        }
    }
    async saveCallerProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerProfile(arg0);
            return result;
        }
    }
    async schema(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.schema();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.schema();
            return result;
        }
    }
    async setSimulationControl(arg0: SimulationControl): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setSimulationControl(to_candid_SimulationControl_n57(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setSimulationControl(to_candid_SimulationControl_n57(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async spotlightAgent(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.spotlightAgent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.spotlightAgent(arg0);
            return result;
        }
    }
    async updateBudget(arg0: bigint, arg1: BudgetInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBudget(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBudget(arg0, arg1);
            return result;
        }
    }
    async updateSavingsGoal(arg0: bigint, arg1: SavingsGoalInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSavingsGoal(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSavingsGoal(arg0, arg1);
            return result;
        }
    }
    async updateTransaction(arg0: bigint, arg1: TransactionInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTransaction(arg0, to_candid_TransactionInput_n5(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTransaction(arg0, to_candid_TransactionInput_n5(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async withdrawTreasury(arg0: string, arg1: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.withdrawTreasury(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.withdrawTreasury(arg0, arg1);
            return result;
        }
    }
}
function from_candid_AgentStatus_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AgentStatus): AgentStatus {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function from_candid_Agent_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Agent): Agent {
    return from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid_Cell_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Cell): Cell {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_Error_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Error): Error_ {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_OrchestrationKind_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrchestrationKind): OrchestrationKind {
    return from_candid_variant_n53(_uploadFile, _downloadFile, value);
}
function from_candid_OrchestrationLogEntry_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrchestrationLogEntry): OrchestrationLogEntry {
    return from_candid_record_n51(_uploadFile, _downloadFile, value);
}
function from_candid_Result__1_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result__1): Result__1 {
    return from_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function from_candid_Result_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_RuleRecord_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RuleRecord): RuleRecord {
    return from_candid_record_n38(_uploadFile, _downloadFile, value);
}
function from_candid_RuleStatus_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RuleStatus): RuleStatus {
    return from_candid_variant_n40(_uploadFile, _downloadFile, value);
}
function from_candid_TradeDirection_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TradeDirection): TradeDirection {
    return from_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function from_candid_TradeRecord_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TradeRecord): TradeRecord {
    return from_candid_record_n28(_uploadFile, _downloadFile, value);
}
function from_candid_TransactionType_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TransactionType): TransactionType {
    return from_candid_variant_n47(_uploadFile, _downloadFile, value);
}
function from_candid_Transaction_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Transaction): Transaction {
    return from_candid_record_n45(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n34(_uploadFile, _downloadFile, value);
}
function from_candid_Value_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Value): Value {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Agent]): Agent | null {
    return value.length === 0 ? null : from_candid_Agent_n22(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Budget]): Budget | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Network]): Network | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_RuleRecord]): RuleRecord | null {
    return value.length === 0 ? null : from_candid_RuleRecord_n37(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SavingsGoal]): SavingsGoal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Transaction]): Transaction | null {
    return value.length === 0 ? null : from_candid_Transaction_n44(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    hasMore: boolean;
    rows: Array<Array<_Cell>>;
}): {
    hasMore: boolean;
    rows: Array<Array<Cell>>;
} {
    return {
        hasMore: value.hasMore,
        rows: from_candid_vec_n13(_uploadFile, _downloadFile, value.rows)
    };
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    value: _Value;
    name: string;
}): {
    value: Value;
    name: string;
} {
    return {
        value: from_candid_Value_n17(_uploadFile, _downloadFile, value.value),
        name: value.name
    };
}
function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _AgentStatus;
    money: number;
    lineage: _Lineage;
    strategy: _Strategy;
    traits: Array<_Trait>;
    name: string;
    generation: bigint;
    knowledgeTimeline: Array<_KnowledgeSnapshot>;
    knowledge: number;
    moneyHistory: Array<_MoneySnapshot>;
}): {
    id: bigint;
    status: AgentStatus;
    money: number;
    lineage: Lineage;
    strategy: Strategy;
    traits: Array<Trait>;
    name: string;
    generation: bigint;
    knowledgeTimeline: Array<KnowledgeSnapshot>;
    knowledge: number;
    moneyHistory: Array<MoneySnapshot>;
} {
    return {
        id: value.id,
        status: from_candid_AgentStatus_n24(_uploadFile, _downloadFile, value.status),
        money: value.money,
        lineage: value.lineage,
        strategy: value.strategy,
        traits: value.traits,
        name: value.name,
        generation: value.generation,
        knowledgeTimeline: value.knowledgeTimeline,
        knowledge: value.knowledge,
        moneyHistory: value.moneyHistory
    };
}
function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    at: _Timestamp;
    id: bigint;
    direction: _TradeDirection;
    token: string;
    agentId: bigint;
    blockIndex: bigint;
    price: number;
    amount: number;
}): {
    at: Timestamp;
    id: bigint;
    direction: TradeDirection;
    token: string;
    agentId: bigint;
    blockIndex: bigint;
    price: number;
    amount: number;
} {
    return {
        at: value.at,
        id: value.id,
        direction: from_candid_TradeDirection_n29(_uploadFile, _downloadFile, value.direction),
        token: value.token,
        agentId: value.agentId,
        blockIndex: value.blockIndex,
        price: value.price,
        amount: value.amount
    };
}
function from_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _RuleStatus;
    domain: string;
    body: string;
    version: bigint;
    contribution: number;
    parent: [] | [bigint];
    createdEpoch: bigint;
}): {
    id: bigint;
    status: RuleStatus;
    domain: string;
    body: string;
    version: bigint;
    contribution: number;
    parent?: bigint;
    createdEpoch: bigint;
} {
    return {
        id: value.id,
        status: from_candid_RuleStatus_n39(_uploadFile, _downloadFile, value.status),
        domain: value.domain,
        body: value.body,
        version: value.version,
        contribution: value.contribution,
        parent: record_opt_to_undefined(from_candid_opt_n41(_uploadFile, _downloadFile, value.parent)),
        createdEpoch: value.createdEpoch
    };
}
function from_candid_record_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    owner: _UserId;
    date: _Timestamp;
    kind: _TransactionType;
    note: string;
    category: string;
    amount: number;
}): {
    id: bigint;
    owner: UserId;
    date: Timestamp;
    kind: TransactionType;
    note: string;
    category: string;
    amount: number;
} {
    return {
        id: value.id,
        owner: value.owner,
        date: value.date,
        kind: from_candid_TransactionType_n46(_uploadFile, _downloadFile, value.kind),
        note: value.note,
        category: value.category,
        amount: value.amount
    };
}
function from_candid_record_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ruleId: [] | [bigint];
    kind: _OrchestrationKind;
    continuationDelta: [] | [number];
    detail: string;
    epoch: bigint;
}): {
    ruleId?: bigint;
    kind: OrchestrationKind;
    continuationDelta?: number;
    detail: string;
    epoch: bigint;
} {
    return {
        ruleId: record_opt_to_undefined(from_candid_opt_n41(_uploadFile, _downloadFile, value.ruleId)),
        kind: from_candid_OrchestrationKind_n52(_uploadFile, _downloadFile, value.kind),
        continuationDelta: record_opt_to_undefined(from_candid_opt_n54(_uploadFile, _downloadFile, value.continuationDelta)),
        detail: value.detail,
        epoch: value.epoch
    };
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    int: bigint;
} | {
    nat: bigint;
} | {
    float: number;
} | {
    bool: boolean;
} | {
    null: null;
} | {
    text: string;
}): {
    __kind__: "int";
    int: bigint;
} | {
    __kind__: "nat";
    nat: bigint;
} | {
    __kind__: "float";
    float: number;
} | {
    __kind__: "bool";
    bool: boolean;
} | {
    __kind__: "null";
    null: null;
} | {
    __kind__: "text";
    text: string;
} {
    return "int" in value ? {
        __kind__: "int",
        int: value.int
    } : "nat" in value ? {
        __kind__: "nat",
        nat: value.nat
    } : "float" in value ? {
        __kind__: "float",
        float: value.float
    } : "bool" in value ? {
        __kind__: "bool",
        bool: value.bool
    } : "null" in value ? {
        __kind__: "null",
        null: value.null
    } : "text" in value ? {
        __kind__: "text",
        text: value.text
    } : value;
}
function from_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: _Error;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_Error_n3(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    alive: null;
} | {
    extinct: null;
} | {
    dormant: null;
} | {
    evolving: null;
}): AgentStatus {
    return "alive" in value ? AgentStatus.alive : "extinct" in value ? AgentStatus.extinct : "dormant" in value ? AgentStatus.dormant : "evolving" in value ? AgentStatus.evolving : value;
}
function from_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    buy: null;
} | {
    sell: null;
}): TradeDirection {
    return "buy" in value ? TradeDirection.buy : "sell" in value ? TradeDirection.sell : value;
}
function from_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    FrontendOriginsNotConfigured: null;
} | {
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    Stale: {
        ageNs: bigint;
    };
} | {
    MalformedCandid: null;
} | {
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    NoAttributes: null;
} | {
    UnknownNonce: null;
} | {
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    MissingField: string;
} | {
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
}): {
    __kind__: "FrontendOriginsNotConfigured";
    FrontendOriginsNotConfigured: null;
} | {
    __kind__: "MixedSsoSources";
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    __kind__: "Stale";
    Stale: {
        ageNs: bigint;
    };
} | {
    __kind__: "MalformedCandid";
    MalformedCandid: null;
} | {
    __kind__: "AmbiguousAttribute";
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    __kind__: "NoAttributes";
    NoAttributes: null;
} | {
    __kind__: "UnknownNonce";
    UnknownNonce: null;
} | {
    __kind__: "UntrustedSsoSource";
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    __kind__: "MissingField";
    MissingField: string;
} | {
    __kind__: "FrontendOriginMismatch";
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
} {
    return "FrontendOriginsNotConfigured" in value ? {
        __kind__: "FrontendOriginsNotConfigured",
        FrontendOriginsNotConfigured: value.FrontendOriginsNotConfigured
    } : "MixedSsoSources" in value ? {
        __kind__: "MixedSsoSources",
        MixedSsoSources: value.MixedSsoSources
    } : "Stale" in value ? {
        __kind__: "Stale",
        Stale: value.Stale
    } : "MalformedCandid" in value ? {
        __kind__: "MalformedCandid",
        MalformedCandid: value.MalformedCandid
    } : "AmbiguousAttribute" in value ? {
        __kind__: "AmbiguousAttribute",
        AmbiguousAttribute: value.AmbiguousAttribute
    } : "NoAttributes" in value ? {
        __kind__: "NoAttributes",
        NoAttributes: value.NoAttributes
    } : "UnknownNonce" in value ? {
        __kind__: "UnknownNonce",
        UnknownNonce: value.UnknownNonce
    } : "UntrustedSsoSource" in value ? {
        __kind__: "UntrustedSsoSource",
        UntrustedSsoSource: value.UntrustedSsoSource
    } : "MissingField" in value ? {
        __kind__: "MissingField",
        MissingField: value.MissingField
    } : "FrontendOriginMismatch" in value ? {
        __kind__: "FrontendOriginMismatch",
        FrontendOriginMismatch: value.FrontendOriginMismatch
    } : value;
}
function from_candid_variant_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    trial: null;
} | {
    active: null;
} | {
    retired: null;
}): RuleStatus {
    return "trial" in value ? RuleStatus.trial : "active" in value ? RuleStatus.active : "retired" in value ? RuleStatus.retired : value;
}
function from_candid_variant_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    expense: null;
} | {
    income: null;
}): TransactionType {
    return "expense" in value ? TransactionType.expense : "income" in value ? TransactionType.income : value;
}
function from_candid_variant_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    trial: null;
} | {
    promotion: null;
} | {
    observation: null;
} | {
    retirement: null;
} | {
    mutation: null;
}): OrchestrationKind {
    return "trial" in value ? OrchestrationKind.trial : "promotion" in value ? OrchestrationKind.promotion : "observation" in value ? OrchestrationKind.observation : "retirement" in value ? OrchestrationKind.retirement : "mutation" in value ? OrchestrationKind.mutation : value;
}
function from_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Array<_Cell>>): Array<Array<Cell>> {
    return value.map((x)=>from_candid_vec_n14(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Cell>): Array<Cell> {
    return value.map((x)=>from_candid_Cell_n15(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TradeRecord>): Array<TradeRecord> {
    return value.map((x)=>from_candid_TradeRecord_n27(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Agent>): Array<Agent> {
    return value.map((x)=>from_candid_Agent_n22(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_OrchestrationLogEntry>): Array<OrchestrationLogEntry> {
    return value.map((x)=>from_candid_OrchestrationLogEntry_n50(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_RuleRecord>): Array<RuleRecord> {
    return value.map((x)=>from_candid_RuleRecord_n37(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Transaction>): Array<Transaction> {
    return value.map((x)=>from_candid_Transaction_n44(_uploadFile, _downloadFile, x));
}
function to_candid_SimulationControl_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SimulationControl): _SimulationControl {
    return to_candid_variant_n58(_uploadFile, _downloadFile, value);
}
function to_candid_TradeDirection_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TradeDirection): _TradeDirection {
    return to_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function to_candid_TransactionInput_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TransactionInput): _TransactionInput {
    return to_candid_record_n6(_uploadFile, _downloadFile, value);
}
function to_candid_TransactionType_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TransactionType): _TransactionType {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    date: Timestamp;
    kind: TransactionType;
    note: string;
    category: string;
    amount: number;
}): {
    date: _Timestamp;
    kind: _TransactionType;
    note: string;
    category: string;
    amount: number;
} {
    return {
        date: value.date,
        kind: to_candid_TransactionType_n7(_uploadFile, _downloadFile, value.kind),
        note: value.note,
        category: value.category,
        amount: value.amount
    };
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TradeDirection): {
    buy: null;
} | {
    sell: null;
} {
    return value == TradeDirection.buy ? {
        buy: null
    } : value == TradeDirection.sell ? {
        sell: null
    } : value;
}
function to_candid_variant_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SimulationControl): {
    resume: null;
} | {
    pause: null;
} {
    return value == SimulationControl.resume ? {
        resume: null
    } : value == SimulationControl.pause ? {
        pause: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TransactionType): {
    expense: null;
} | {
    income: null;
} {
    return value == TransactionType.expense ? {
        expense: null
    } : value == TransactionType.income ? {
        income: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
